---
- name: K3S Infrastructure Setup
  hosts: server
  become: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages for Incus
      ansible.builtin.apt:
        update_cache: true
        install_recommends: true
        name: incus
        state: present

    - name: Create incus-admin group if it doesn't exist
      ansible.builtin.group:
        name: incus-admin
        state: present

    - name: Add user to incus-admin group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: incus-admin
        append: yes

    - name: Create Incus initialization service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Initialize Incus
          After=incus.service
          Wants=incus.service

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/incus admin init --minimal
          User={{ ansible_user }}
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/incus-init.service
        mode: "0644"

    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: yes

    - name: Enable and start Incus initialization service
      ansible.builtin.systemd_service:
        name: incus-init
        state: started
        enabled: yes

    - name: Wait for Incus to be ready
      ansible.builtin.wait_for:
        port: 8443
        host: localhost
        delay: 5
        timeout: 30

    - name: Check if Incus is initialized
      ansible.builtin.shell: incus info
      become_user: "{{ ansible_user }}"
      register: incus_status
      failed_when: false

    - name: Initialize Incus if needed
      ansible.builtin.shell: incus admin init --auto
      become_user: "{{ ansible_user }}"
      when: incus_status.rc != 0

