---
- name: K3s prerequisites
  hosts: k3s
  gather_facts: true
  become: true
  vars_files:
    - variables.yaml
  pre_tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:
        timeout: 120
  roles:
    - role: k3s.orchestration.prereq
- name: K3s server
  hosts: k3s_server
  gather_facts: false
  become: true
  vars_files:
    - variables.yaml
  vars:
    api_endpoint: "{{ hostvars['k3s_control_plane']['ansible_host'] }}"
  roles:
    - role: k3s.orchestration.k3s_server
- name: K3s agents
  hosts: k3s_workers
  gather_facts: false
  become: true
  vars_files:
    - variables.yaml
  vars:
    api_endpoint: '{{ hostvars[''k3s_control_plane''][''ansible_host''] }}'
  roles:
    - role: k3s.orchestration.k3s_agent
- name: Verify cluster
  hosts: k3s_server
  gather_facts: false
  become: true
  vars_files:
    - variables.yaml
  tasks:
    - name: Wait for all nodes to reach Ready state
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=Ready nodes --all --timeout=300s
      changed_when: false
    - name: Show cluster nodes
      ansible.builtin.command:
        cmd: kubectl get nodes -o wide
      changed_when: false
      register: nodes_output
    - name: Print cluster nodes
      ansible.builtin.debug:
        msg: '{{ nodes_output.stdout_lines }}'
