apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${secret_name}
  namespace: ${namespace}
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: ${project_slug}
        envSlug: ${env_slug}
        secretsPath: /
        recursive: true
      credentialsRef:
        secretName: ${auth_secret_name}
        secretNamespace: ${auth_secret_namespace}
  managedKubeSecretReferences:
    - secretName: ${secret_name}
      secretNamespace: ${namespace}
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
