creation_rules:
  - path_regex: .*terraform\.tfvars\.json(\.sops)?$
    gcp_kms: projects/rj-iplanrio-dia/locations/global/keyRings/terraform-k3s/cryptoKeys/sops-prod
    input_type: json
    output_type: json
