#cloud-config
package_update: true
packages:
  - curl
write_files:
  - path: /var/lib/cloud/scripts/per-once/install-k3s-agent.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      until curl -k https://${master_ip}:6443/ping; do
        echo "Waiting for K3s server..."
        sleep 10
      done

      curl -sfL https://get.k3s.io | K3S_URL=https://${master_ip}:6443 K3S_TOKEN=${k3s_token} sh -s - agent \
        --kubelet-arg="image-gc-high-threshold=75" \
        --kubelet-arg="image-gc-low-threshold=60" \
        --kubelet-arg="container-log-max-size=10Mi" \
        --kubelet-arg="container-log-max-files=3" \
        --kubelet-arg="eviction-hard=memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi" \
        --kubelet-arg="eviction-soft=memory.available<200Mi,nodefs.available<1.5Gi" \
        --kubelet-arg="eviction-soft-grace-period=memory.available=2m,nodefs.available=2m" \
        --kubelet-arg="eviction-max-pod-grace-period=60" \
        --kubelet-arg="volume-stats-agg-period=1m"
