#cloud-config
package_update: true
packages:
  - curl
write_files:
  - path: /var/lib/cloud/scripts/per-once/install-k3s.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      curl -sfL https://get.k3s.io | K3S_TOKEN=${k3s_token} sh -s - --write-kubeconfig-mode 644
